name: param-experience
region: blr
static_sites:
  - name: web
    github:
      repo: paramwebsite/Experience
      branch: main
      deploy_on_push: true
    build_command: CI=false npm run build
    output_dir: build
    index_document: index.html
    catchall_document: index.html
    envs:
      - key: REACT_APP_API_ENDPOINT
        scope: BUILD_TIME
        value: https://admindashboard.paramscience.org
      - key: REACT_APP_VISIT_US_DEPLOYMENT_ID
        scope: BUILD_TIME
        value: PASTE_YOURS
      - key: REACT_APP_VISIT_US_API_ENDPOINT
        scope: BUILD_TIME
        value: PASTE_YOURS
      - key: REACT_APP_BOOK_MY_SHOW_URL
        scope: BUILD_TIME
        value: PASTE_YOURS